//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNPPoly.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NNPPoly.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap adduser {
            get {
                object obj = ResourceManager.GetObject("adduser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_plain_blue_E {
            get {
                object obj = ResourceManager.GetObject("arrow_plain_blue_E", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_plain_blue_W {
            get {
                object obj = ResourceManager.GetObject("arrow_plain_blue_W", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_plain_green_W {
            get {
                object obj = ResourceManager.GetObject("arrow_plain_green_W", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blue_records {
            get {
                object obj = ResourceManager.GetObject("blue_records", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ClientPanel {
            get {
                object obj = ResourceManager.GetObject("ClientPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap collection_list {
            get {
                object obj = ResourceManager.GetObject("collection_list", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Company {
            get {
                object obj = ResourceManager.GetObject("Company", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DebitAdvisePrintFormat {
            get {
                object obj = ResourceManager.GetObject("DebitAdvisePrintFormat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DebitNoteFormat {
            get {
                object obj = ResourceManager.GetObject("DebitNoteFormat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DebitNotePrintFormat {
            get {
                object obj = ResourceManager.GetObject("DebitNotePrintFormat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] envelope_withDesign {
            get {
                object obj = ResourceManager.GetObject("envelope_withDesign", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] envelope_withoutDesign {
            get {
                object obj = ResourceManager.GetObject("envelope_withoutDesign", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;style&gt;
        ///		tr.head td {
        ///			background-color:gray;
        ///			color:white;
        ///			font-size:14px;
        ///		}
        ///		tr.subhead td {
        ///			background-color:lightgray;
        ///			color:black;
        ///			font-size:13px;
        ///		}
        ///		
        ///		td {
        ///			font-size:12px;
        ///			border-color:gray;
        ///			padding:2px;
        ///			font-weight:bold;
        ///		}
        ///		
        ///		tr.highlight1 td {
        ///			background-color:red;
        ///			color:white;
        ///		}
        ///		
        ///		tr.highlight2 td {
        ///			background-color:green;
        ///			color:black;
        ///		}
        ///		
        ///		body {
        ///			padding:5px;
        ///			margin:0px auto;
        ///		}
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string htmlMoUReport {
            get {
                return ResourceManager.GetString("htmlMoUReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;style&gt;
        ///		tr.head td {
        ///			background-color:gray;
        ///			color:white;
        ///			font-size:14px;
        ///		}
        ///		tr.subhead td {
        ///			background-color:lightgray;
        ///			color:black;
        ///			font-size:13px;
        ///		}
        ///		
        ///		td {
        ///			font-size:12px;
        ///			border-color:gray;
        ///			padding:2px;
        ///			font-weight:bold;
        ///		}
        ///		
        ///		tr.highlight1 td {
        ///			background-color:red;
        ///			color:white;
        ///		}
        ///		
        ///		tr.highlight2 td {
        ///			background-color:green;
        ///			color:black;
        ///		}
        ///		
        ///		body {
        ///			padding:5px;
        ///			margin:0px;
        ///		}
        ///		tr.fo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string htmlReportCode {
            get {
                return ResourceManager.GetString("htmlReportCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr class=&quot;%hclass%&quot;&gt;
        ///			&lt;td align=&quot;right&quot;&gt;%NEW DATE%&lt;/td&gt;
        ///			&lt;td align=&quot;right&quot;&gt;%LAST DATE%&lt;/td&gt;
        ///			&lt;td align=&quot;right&quot;&gt;%DATE1%&lt;/td&gt;
        ///			&lt;td align=&quot;left&quot;&gt;%INVOICE NO%&lt;/td&gt;
        ///			&lt;td align=&quot;right&quot;&gt;%MT%&lt;/td&gt;
        ///			&lt;td align=&quot;right&quot;&gt;%AMT1%&lt;/td&gt;
        ///			&lt;td align=&quot;right&quot; style=&quot;background-color:%bg%;color:%fg%&quot;&gt;%AMT4%&lt;/td&gt;
        ///			&lt;td align=&quot;right&quot; style=&quot;background-color:%bg%;color:%fg%&quot;&gt;%AMT2%&lt;/td&gt;
        ///			&lt;td align=&quot;left&quot; style=&quot;background-color:%bg%;color:%fg%&quot;&gt;%CH NO%&lt;/td&gt;
        ///			&lt;td align=&quot;right&quot; style=&quot;background-color:%b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string htmlTRCode {
            get {
                return ResourceManager.GetString("htmlTRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap interestadviselist {
            get {
                object obj = ResourceManager.GetObject("interestadviselist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap no {
            get {
                object obj = ResourceManager.GetObject("no", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paste {
            get {
                object obj = ResourceManager.GetObject("paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PaymentEntryTemplate {
            get {
                object obj = ResourceManager.GetObject("PaymentEntryTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PaymentEntryTemplateMacroEnabled {
            get {
                object obj = ResourceManager.GetObject("PaymentEntryTemplateMacroEnabled", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plus_blue {
            get {
                object obj = ResourceManager.GetObject("plus_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plus_green {
            get {
                object obj = ResourceManager.GetObject("plus_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap simpleuser {
            get {
                object obj = ResourceManager.GetObject("simpleuser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Spreadsheet {
            get {
                object obj = ResourceManager.GetObject("Spreadsheet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap table_pencil_green {
            get {
                object obj = ResourceManager.GetObject("table_pencil_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap table_reload {
            get {
                object obj = ResourceManager.GetObject("table_reload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tag_blue {
            get {
                object obj = ResourceManager.GetObject("tag_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap train {
            get {
                object obj = ResourceManager.GetObject("train", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wcodez.NNPPoly.
        /// </summary>
        internal static string uid {
            get {
                return ResourceManager.GetString("uid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.4.
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wcodez {
            get {
                object obj = ResourceManager.GetObject("wcodez", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
