//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNPPoly.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NNPPoly.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DebitAdvisePrintFormat {
            get {
                object obj = ResourceManager.GetObject("DebitAdvisePrintFormat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DebitNoteFormat {
            get {
                object obj = ResourceManager.GetObject("DebitNoteFormat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DebitNotePrintFormat {
            get {
                object obj = ResourceManager.GetObject("DebitNotePrintFormat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;style&gt;
        ///		tr.head td {
        ///			background-color:gray;
        ///			color:white;
        ///			font-size:14px;
        ///		}
        ///		tr.subhead td {
        ///			background-color:lightgray;
        ///			color:black;
        ///			font-size:13px;
        ///		}
        ///		
        ///		td {
        ///			font-size:12px;
        ///			border-color:gray;
        ///			padding:2px;
        ///			font-weight:bold;
        ///		}
        ///		
        ///		tr.highlight1 td {
        ///			background-color:red;
        ///			color:white;
        ///		}
        ///		
        ///		tr.highlight2 td {
        ///			background-color:green;
        ///			color:black;
        ///		}
        ///		
        ///		body {
        ///			padding:5px;
        ///			margin:0px;
        ///		}
        ///		tr.fo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string html {
            get {
                return ResourceManager.GetString("html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr class=&quot;%hclass%&quot;&gt;
        ///			&lt;td align=&quot;right&quot;&gt;%NEW DATE%&lt;/td&gt;
        ///			&lt;td align=&quot;right&quot;&gt;%LAST DATE%&lt;/td&gt;
        ///			&lt;td align=&quot;right&quot;&gt;%DATE1%&lt;/td&gt;
        ///			&lt;td align=&quot;left&quot;&gt;%INVOICE NO%&lt;/td&gt;
        ///			&lt;td align=&quot;right&quot;&gt;%MT%&lt;/td&gt;
        ///			&lt;td align=&quot;right&quot;&gt;%AMT1%&lt;/td&gt;
        ///			&lt;td align=&quot;right&quot; style=&quot;background-color:%bg%;color:%fg%&quot;&gt;%AMT4%&lt;/td&gt;
        ///			&lt;td align=&quot;right&quot; style=&quot;background-color:%bg%;color:%fg%&quot;&gt;%AMT2%&lt;/td&gt;
        ///			&lt;td align=&quot;left&quot; style=&quot;background-color:%bg%;color:%fg%&quot;&gt;%CH NO%&lt;/td&gt;
        ///			&lt;td align=&quot;right&quot; style=&quot;background-color:%b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string trRep {
            get {
                return ResourceManager.GetString("trRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap webcodez_infoway {
            get {
                object obj = ResourceManager.GetObject("webcodez infoway", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
